version = 1

[[annotations]]
path = [
    "Tests/SpeziConsentTests/Resources/*.pdf",
    "Tests/SpeziConsentTests/Resources/*.md"
]
SPDX-FileCopyrightText = "2024 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"
