version = 1

[[annotations]]
path = [
    "Tests/SpeziConsentTests/Resources/**",
    "Tests/TestApp/Resources/**"
]
SPDX-FileCopyrightText = "2024 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"
