#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: Build-and-Test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package_tests:
    name: Build and Test Swift Package ${{ matrix.destination }}
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    strategy:
      matrix:
        include:
          - platform: iOS
            destination: 'platform=iOS Simulator,name=iPhone 16 Pro'
          - platform: macOS
            destination: 'platform=macOS,name=My Mac'
          - platform: visionOS
            destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziConsent
      destination: ${{ matrix.destination }}
      resultBundle: ${{ format('SpeziConsent-{0}.xcresult', matrix.platform) }}
      artifactname: ${{ format('SpeziConsent-{0}.xcresult', matrix.platform) }}
  ui_tests:
    name: Build and Test UI Tests
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    strategy:
      matrix:
        include:
          - platform: iOS
            destination: 'platform=iOS Simulator,name=iPhone 16 Pro'
          - platform: iPadOS
            destination: 'platform=iOS Simulator,name=iPad Air 13-inch (M3)'
          - platform: visionOS
            destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      destination: ${{ matrix.destination }}
      resultBundle: ${{ format('TestApp-{0}.xcresult', matrix.platform) }}
      artifactname: ${{ format('TestApp-{0}.xcresult', matrix.platform) }}
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [package_tests, ui_tests]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziConsent-*.xcresult TestApp-*.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
