#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: Build-and-Test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  packageios:
    name: Build and Test Swift Package iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziConsent
      resultBundle: SpeziConsent-iOS.xcresult
      artifactname: SpeziConsent-iOS.xcresult
  packagevisionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziConsent
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: SpeziConsent-visionOS.xcresult
      artifactname: SpeziConsent-visionOS.xcresult
  packagemacos:
    name: Build and Test Swift Package macOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziConsent
      resultBundle: SpeziConsent-macOS.xcresult
      destination: 'platform=macOS,arch=arm64'
      artifactname: SpeziConsent-macOS.xcresult
  ios:
    name: Build and Test iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      resultBundle: TestApp-iOS.xcresult
      artifactname: TestApp-iOS.xcresult
  ipados:
    name: Build and Test iPadOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      destination: 'platform=iOS Simulator,name=iPad Air 13-inch (M2)'
      resultBundle: TestApp-iPadOS.xcresult
      artifactname: TestApp-iPadOS.xcresult
  visionos:
    name: Build and Test visionOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: TestApp-visionOS.xcresult
      artifactname: TestApp-visionOS.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [packageios, packagevisionos, packagemacos, ios, ipados, visionos]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziConsent-iOS.xcresult SpeziConsent-visionOS.xcresult SpeziConsent-macOS.xcresult TestApp-iOS.xcresult TestApp-iPadOS.xcresult TestApp-visionOS.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
